// Converts raw Iconly SVGs (batch-exported from Figma, see docs/figma-sync.md
// "Icons") into typed React icon components.
//
// Input:  src/icons/svg/*.svg  — one file per icon, named in kebab-case
//         (e.g. "arrow-right.svg" for "Iconly/Sharp/Light/Arrow - Right").
//         Figma's export nests the real geometry inside a single
//         <g id="Iconly/..."> group alongside page-background bleed from the
//         enclosing frame — this script extracts just that group.
// Output: src/icons/generated/{PascalCase}Icon.tsx — one component per icon,
//         plus an index.ts barrel and a name -> component registry.
//
// Usage: pnpm --filter @lumen/ui icons:import
// Re-run any time src/icons/svg/ changes (new exports, updated icons).

import { readdir, readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { optimize } from "svgo";

const here = dirname(fileURLToPath(import.meta.url));
const svgDir = join(here, "../src/icons/svg");
const outDir = join(here, "../src/icons/generated");

const ICON_GROUP_RE = /<g[^>]*id="Iconly\/[^"]*"[^>]*>([\s\S]*?)<\/g>/;
const FIXED_COLOR_RE = /(fill|stroke)="#[0-9a-fA-F]{3,8}"/g;

function toPascalCase(kebab) {
  return kebab
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function extractIconGroup(rawSvg, fileName) {
  const match = rawSvg.match(ICON_GROUP_RE);
  if (!match) {
    throw new Error(
      `${fileName}: couldn't find a <g id="Iconly/..."> group. This script assumes ` +
        `Figma's export nests real geometry one level deep inside that group with no ` +
        `further nested <g> elements — inspect the raw export and adjust ICON_GROUP_RE ` +
        `if the icon set's structure differs.`
    );
  }
  return match[1].replace(FIXED_COLOR_RE, '$1="currentColor"');
}

async function buildIconSvg(innerMarkup) {
  const wrapped = `<svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">${innerMarkup}</svg>`;
  const { data } = optimize(wrapped, {
    multipass: true,
    plugins: [
      {
        name: "preset-default",
        params: {
          overrides: {
            removeViewBox: false,
            // currentColor isn't a real color to SVGO's minifyStyles pass — leave as-is.
            removeUselessDefs: false
          }
        }
      }
    ]
  });
  // Pull the inner markup back out of SVGO's cleaned document.
  const cleaned = data.match(/<svg[^>]*>([\s\S]*)<\/svg>/)?.[1] ?? innerMarkup;
  // JSX requires camelCase SVG attributes (stroke-width -> strokeWidth) —
  // React renders kebab-case ones fine but warns on every mount.
  return cleaned
    .trim()
    .replace(/([a-z]+)-([a-z]+)=/g, (_, a, b) => `${a}${b[0].toUpperCase()}${b.slice(1)}=`);
}

function componentSource(componentName, innerSvg) {
  return `import { forwardRef, type SVGProps } from "react";

/** Generated by scripts/icons-import.mjs — do not edit by hand. */
export const ${componentName} = forwardRef<SVGSVGElement, SVGProps<SVGSVGElement>>(
  (props, ref) => (
    <svg
      ref={ref}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      width="1em"
      height="1em"
      aria-hidden="true"
      {...props}
    >
      ${innerSvg}
    </svg>
  )
);
${componentName}.displayName = "${componentName}";
`;
}

async function main() {
  const files = (await readdir(svgDir)).filter((f) => f.endsWith(".svg"));
  if (files.length === 0) {
    console.error(`No .svg files found in ${svgDir}`);
    process.exit(1);
  }

  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });

  const icons = [];

  for (const file of files.sort()) {
    const kebabName = file.replace(/\.svg$/, "");
    const componentName = `${toPascalCase(kebabName)}Icon`;
    const raw = await readFile(join(svgDir, file), "utf8");
    const innerMarkup = extractIconGroup(raw, file);
    const cleanedInner = await buildIconSvg(innerMarkup);
    await writeFile(join(outDir, `${componentName}.tsx`), componentSource(componentName, cleanedInner));
    icons.push({ kebabName, componentName });
  }

  const indexSource =
    icons.map((i) => `export { ${i.componentName} } from "./${i.componentName}";`).join("\n") + "\n";
  await writeFile(join(outDir, "index.ts"), indexSource);

  const registrySource = `import type { ForwardRefExoticComponent, RefAttributes, SVGProps } from "react";
${icons.map((i) => `import { ${i.componentName} } from "./${i.componentName}";`).join("\n")}

type IconComponent = ForwardRefExoticComponent<SVGProps<SVGSVGElement> & RefAttributes<SVGSVGElement>>;

/** Generated by scripts/icons-import.mjs — do not edit by hand. */
export const iconRegistry: Record<string, IconComponent> = {
${icons.map((i) => `  "${i.kebabName}": ${i.componentName}`).join(",\n")}
};

export type IconName = keyof typeof iconRegistry;
`;
  await writeFile(join(outDir, "registry.ts"), registrySource);

  console.log(`icons:import complete -> generated ${icons.length} icon components in ${outDir}`);
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
